---
apiVersion: v1
kind: Service
metadata:
  name: apisix
  namespace: ns-apim
spec:
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  - name: tls
    port: 9443
    protocol: TCP
    targetPort: 9443
  - name: prom
    port: 9091
    protocol: TCP
    targetPort: 9091
  - name: admin
    port: 9180
    protocol: TCP
    targetPort: 9180
  selector:
    app.kubernetes.io/instance: apisix
    app.kubernetes.io/name: apisix
  sessionAffinity: None
  type: ClusterIP
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: apisix-nodeport
#  namespace: ns-apim
#spec:
#  ports:
#  - name: http
#    nodePort: 32003
#    port: 9080
#    protocol: TCP
#    targetPort: 9080
#  - name: tls
#    nodePort: 32004
#    port: 9443
#    protocol: TCP
#    targetPort: 9443
#  - name: prom
#    nodePort: 32005
#    port: 9091
#    protocol: TCP
#    targetPort: 9091
#  - name: admin
#    nodePort: 32018
#    port: 9180
#    protocol: TCP
#    targetPort: 9180
#  selector:
#    app.kubernetes.io/instance: apisix
#    app.kubernetes.io/name: apisix
#  sessionAffinity: None
#  type: NodePort
