apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-pushgateway
  name: prometheus-pushgateway
  namespace: ns-monitor
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus-pushgateway
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-pushgateway
    spec:
      containers:
      - image: registry.easesaas.com/myron/pushgateway:v1.6.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/ready
            port: 9091
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: prometheus-pushgateway
        ports:
        - containerPort: 9091
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/ready
            port: 9091
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources: 
          limits:
            cpu: 250m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 250Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: storage-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: storage-volume
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/probe: pushgateway
  labels:
    app: prometheus-pushgateway
  name: prometheus-pushgateway
  namespace: ns-monitor
spec:
  selector:
    app: prometheus-pushgateway
  ports:
  - name: http
    port: 9091
    protocol: TCP
    targetPort: 9091
  type: ClusterIP
#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: prometheus-pushgateway
#  name: prometheus-pushgateway-lb
#  namespace: ns-monitor
#spec:
#  selector:
#    app: prometheus-pushgateway
#  ports:
#  - name: http
#    port: 9091
#    protocol: TCP
#    targetPort: 9091
#  type: NodePort
