apiVersion: v1
kind: ConfigMap
metadata:
  name: alarm-settings-config
  namespace: ns-monitor
data:
  alarm-settings.yml: |-
    rules:
      # Rule unique name, must be ended with `_rule`.
      # 服务层级：
      service_resp_time_rule:
        metrics-name: service_resp_time
        op: ">"
        threshold: 10000
        period: 5
        count: 3
        silence-period: 5
        tags:
          level: "critical"
        message: "服务:【{name}】\n指标: 响应时间\n详情: 至少3次超过10s(最近5分钟内)"

      service_sla_rule:
        # Metrics value need to be long, double or int
        metrics-name: service_sla
        op: "<"
        threshold: 9000
        # The length of time to evaluate the metrics
        period: 5
        # How many times after the metrics match the condition, will trigger alarm
        count: 2
        # How many times of checks, the alarm keeps silence after alarm triggered, default as same as period.
        silence-period: 5
        tags:
          level: "critical"
        message: "服务:【{name}】\n指标: 成功率\n详情: 至少2次低于90%(最近5分钟内)"

      endpoint_relation_resp_time_rule:
        metrics-name: endpoint_resp_time
        threshold: 10000
        op: ">"
        period: 5
        count: 3
        tags:
          level: "critical"
        message: "接口:【{name}】\n指标: 响应时间\n详情: 至少3次超过10s(最近5分钟内)"


      # 数据库层级
      database_access_resp_time_rule:
        metrics-name: database_access_resp_time
        threshold: 10000
        op: ">"
        period: 5
        count: 3
        tags:
          level: "critical"
        message: "数据库: 【{name}】\n指标：响应时间\n详情: 至少3次超过10s(最近5分钟内)"

      # K8S 监控
      # k9s_pod_restarts_rule:
      #   metrics-name: k8s_service_pod_status_restarts_total
      #   threshold: 1
      #   op: ">"
      #   period: 5
      #   count: 3
      #   tags:
      #     level: "critical"
      #   message: k8s服务【{name}】pod自动重启次数大于1次

    
    #webhooks:
    #  - http://127.0.0.1/notify/
    #  - http://127.0.0.1/go-wechat/
    #  - http://prometheus-alert-center.ns-monitor.svc:8080/prometheusalert?type=email&tpl=sw-techsun-email&email=barry@techsun.com
    #  - http://prometheus-alert-center.ns-monitor.svc:8080/prometheusalert?type=txdh&tpl=sw-techsun-dh&phone=13794125235
    #  - http://prometheus-alert-center.ns-monitor.svc:8080/prometheusalert?type=txdx&tpl=sw-techsun-dx&phone=13794125235
    
    feishuHooks:
      textTemplate: |-
                {
                  "msg_type": "text",
                  "content": {
                    "text": "Socialhub-huawei-prodyjd SkyWalking Alarm: \n%s."
                  }
                }
      webhooks:
        - url: https://open.feishu.cn/open-apis/bot/v2/hook/1a37497e-c951-4a06-8e1f-a27d655bec02
        
      #dingtalkHooks:
      #  textTemplate: |-
      #    {
      #      "msgtype": "text",
      #      "text": {
      #        "content": "Apache SkyWalking Alarm: \n %s."
      #      }
      #    }
      #  webhooks:
      #    - https://open.feishu.cn/open-apis/bot/v2/hook/7c9715b4-2a8f-461b-a459-e05512f51213
