apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    everest.io/enterprise-project-id: "0"
    pv.kubernetes.io/bind-completed: "yes"
    volume.beta.kubernetes.io/storage-provisioner: everest-csi-provisioner
  creationTimestamp: "2023-12-27T02:49:02Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: powerjob-log-prod-pvc
  namespace: prod
  resourceVersion: "96084968"
  uid: b6c798d7-a1e2-44cf-bafd-9f8c05b0acc5
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: csi-sfsturbo
  volumeMode: Filesystem
  volumeName: pv-efs-powerjob-log
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 500Gi
  phase: Bound
