#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: prometheus-pv
#  labels:
#    app: prometheus
#spec:
#  accessModes:
#  - ReadWriteOnce
#  capacity:
#    storage: 128Gi
#  storageClassName: cephfs
#  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: ns-monitor
spec:
  selector:
    matchLabels:
      app: prometheus
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
  storageClassName: csi-disk
