apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: skywalking
    component: oap
  name: skywalking-oap-cm-override
  namespace: ns-monitor
data:
  alarm-settings.yml: |-
    rules:
      # Rule unique name, must be ended with `_rule`.
      # 服务层级：
      service_resp_time_rule:
        metrics-name: service_resp_time
        op: ">"
        threshold: 10000
        period: 5
        count: 3
        silence-period: 5
        tags:
          level: "critical"
        message: "服务:【{name}】\n指标: 响应时间\n详情: 至少3次超过10s(最近5分钟内)"

      service_sla_rule:
        # Metrics value need to be long, double or int
        metrics-name: service_sla
        op: "<"
        threshold: 9000
        # The length of time to evaluate the metrics
        period: 5
        # How many times after the metrics match the condition, will trigger alarm
        count: 2
        # How many times of checks, the alarm keeps silence after alarm triggered, default as same as period.
        silence-period: 5
        tags:
          level: "critical"
        message: "服务:【{name}】\n指标: 成功率\n详情: 至少2次低于90%(最近5分钟内)"

      endpoint_relation_resp_time_rule:
        metrics-name: endpoint_resp_time
        threshold: 10000
        op: ">"
        period: 5
        count: 3
        tags:
          level: "critical"
        message: "接口:【{name}】\n指标: 响应时间\n详情: 至少3次超过10s(最近5分钟内)"


      # 数据库层级
      database_access_resp_time_rule:
        metrics-name: database_access_resp_time
        threshold: 10000
        op: ">"
        period: 5
        count: 3
        tags:
          level: "critical"
        message: "数据库: 【{name}】\n指标：响应时间\n详情: 至少3次超过10s(最近5分钟内)"


    filter-expression: '!message.matches(".*\\/synchrony-proxy\\/v1.*") && !message.matches(".*\\/download\\/attachments.*")' 
     
    feishuHooks:
      textTemplate: |-
        {
          "msg_type": "post",
          "content": {
            "post": {
              "zh_cn": {
                "title": "Socialhub-huawei-prodsg SkyWalking Alarm",
                "content": [
                  [
                    {
                      "tag": "text",
                      "un_escape": true,
                      "text": "%s"
                    }
                  ]
                ]
              }
            }
          }
        }
      webhooks:
      - url: https://open.feishu.cn/open-apis/bot/v2/hook/1a37497e-c951-4a06-8e1f-a27d655bec02


  core.default.log4j-xml: |
    <Configuration status="WARN">
       <Appenders>
         <Console name="Console"target="SYSTEM_OUT">
           <PatternLayout charset="UTF-8"pattern="%d - %c - %L [%t] %-5p %x - %m%n"/>
         </Console>
       </Appenders>
       <Loggers>
         <logger name="io.grpc.netty"level="INFO"/>
         <logger name="org.apache.skywalking.oap.server.configuration.api"level="TRACE"/>
         <logger name="org.apache.skywalking.oap.server.configuration.configmap"level="DEBUG"/>
         <Root level="INFO">
           <AppenderRef ref="Console"/>
         </Root>
        </Loggers>
    </Configuration>
  metadata-service-mapping.yaml: |
    serviceName: mesh-svr::${LABELS."service.istio.io/canonical-name",LABELS."app.kubernetes.io/name",LABELS.app}
    serviceInstanceName: ${NAME}

