apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: skywalking
    component: oap
  name: skywalking-oap
  namespace: ns-monitor
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: skywalking
      component: oap
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: skywalking
        component: oap
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: skywalking
                  component: oap
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - env:
        - name: JAVA_OPTS
          value: -Dmode=no-init -Xmx4g -Xms4g
        - name: SW_CLUSTER
          value: kubernetes
        - name: SW_CLUSTER_K8S_NAMESPACE
          value: ns-monitor
        - name: SW_CLUSTER_K8S_LABEL
          value: app=skywalking,component=oap
        - name: SKYWALKING_COLLECTOR_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: SW_STORAGE
          value: elasticsearch
        - name: SW_STORAGE_ES_CLUSTER_NODES
          valueFrom:
            secretKeyRef:
              name: sw-storage-secret
              key: sw_es_cluster
        - name: SW_ES_USER
          valueFrom:
            secretKeyRef:
              name: sw-storage-secret
              key: sw_es_user
        - name: SW_ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sw-storage-secret
              key: sw_es_password
        - name: K8S_SERVICE_NAME_RULE
          value: mesh-svr::${service.metadata.name}
        - name: SW_CONFIGURATION
          value: k8s-configmap
        - name: SW_ENABLE_ON_DEMAND_POD_LOG
          value: "true"
        - name: SW_ENABLE_UPDATE_UI_TEMPLATE
          value: "false"
        - name: SW_ENVOY_METRIC_ALS_HTTP_ANALYSIS
          value: mx-mesh,persistence
        - name: SW_ENVOY_METRIC_ALS_TCP_ANALYSIS
          value: mx-mesh
        - name: SW_HEALTH_CHECKER
          value: default
        - name: SW_METER_ANALYZER_ACTIVE_FILES
          value: datasource,threadpool,satellite,network-profiling,spring-sleuth
        - name: SW_OTEL_RECEIVER
          value: default
        - name: SW_OTEL_RECEIVER_ENABLED_OTEL_RULES
          value: vm,oap,k8s/*,istio-controlplane,mysql/*,postgresql/*,apisix,elasticsearch/*
        - name: SW_QUERY_ZIPKIN
          value: default
        - name: SW_RECEIVER_ZIPKIN
          value: default
        - name: SW_SLOW_DB_THRESHOLD
          value: default:0,mongodb:100
        - name: SW_STORAGE_ES_INDEX_SHARDS_NUMBER
          value: "6"
        - name: SW_STORAGE_ES_RESPONSE_TIMEOUT
          value: "50000"
        - name: SW_STORAGE_ES_SUPER_DATASET_INDEX_SHARDS_FACTOR
          value: "2"
        - name: SW_TELEMETRY
          value: prometheus
        image: registry.easesaas.com/myron/skywalking-oap-server:9.5.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 12800
          timeoutSeconds: 1
        name: oap
        ports:
        - containerPort: 11800
          name: grpc
          protocol: TCP
        - containerPort: 1234
          name: metrics
          protocol: TCP
        - containerPort: 9090
          name: promql
          protocol: TCP
        - containerPort: 12800
          name: rest
          protocol: TCP
        - containerPort: 9411
          name: zipkin
          protocol: TCP
        - containerPort: 9412
          name: zipkin-query
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 12800
          timeoutSeconds: 1
        resources: {}
        startupProbe:
          failureThreshold: 9
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 12800
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /skywalking/config/alarm-settings.yml
          name: skywalking-oap-override
          subPath: alarm-settings.yml
        - mountPath: /skywalking/config/core.default.log4j-xml
          name: skywalking-oap-override
          subPath: core.default.log4j-xml
        - mountPath: /skywalking/config/metadata-service-mapping.yaml
          name: skywalking-oap-override
          subPath: metadata-service-mapping.yaml
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - for i in $(seq 1 60); do nc -z -w3 elasticsearch-master.ns-elastic.svc 9200
          && exit 0 || sleep 5; done; exit 1
        image: busybox:1.30
        imagePullPolicy: IfNotPresent
        name: wait-for-elasticsearch
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: skywalking-oap
      serviceAccountName: skywalking-oap
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: skywalking-oap-cm-override
        name: skywalking-oap-override

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: skywalking
    component: oap
  name: skywalking-oap
  namespace: ns-monitor
spec:
  ports:
  - name: grpc
    port: 11800
    protocol: TCP
    targetPort: 11800
  - name: metrics
    port: 1234
    protocol: TCP
    targetPort: 1234
  - name: promql
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: rest
    port: 12800
    protocol: TCP
    targetPort: 12800
  - name: zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  - name: zipkin-query
    port: 9412
    protocol: TCP
    targetPort: 9412
  selector:
    app: skywalking
    component: oap
  sessionAffinity: None
  type: ClusterIP

