apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: skywalking
    component: ui
  name: skywalking-ui
  namespace: ns-monitor
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: skywalking
      component: ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: skywalking
        component: ui
    spec:
      containers:
      - env:
        - name: SW_OAP_ADDRESS
          value: http://skywalking-oap.ns-monitor.svc:12800
        - name: SW_ZIPKIN_ADDRESS
          value: http://skywalking-oap.ns-monitor.svc:9412
        image: registry.easesaas.com/myron/skywalking-ui:9.5.x
        imagePullPolicy: IfNotPresent
        name: ui
        ports:
        - containerPort: 8080
          name: page
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: skywalking
    component: ui
  name: skywalking-ui
  namespace: ns-monitor
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: skywalking
    component: ui
  sessionAffinity: None
  type: ClusterIP

