metadata:
- appName: ''
  dataId: customer-events-service-tool.yaml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
- appName: ''
  dataId: customer-service-tool.yaml
  desc: ''
  group: DEFAULT_GROUP
  type: yaml
