server:
  tomcat:
    max-threads: 600
    max-http-header-size: 819
spring:
  main:
    allow-bean-definition-overriding: true
      
#feign开启熔断器
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
    connection-timeout: 8000
  client:
    config:
      portraitcenter:
        readTimeout: 600000
ribbon:
  # 连接超时时间(ms)
  ConnectTimeout: 4000
  # 通信超时时间(ms)
  ReadTimeout: 4000
    
    
# 熔断超时时间的配置
hystrix:
  threadpool:
    default:
      # 并发执行的最大线程数，默认10
      coreSize: 300
      # BlockingQueue的最大队列数
      maxQueueSize: 300
  command:
    default:
      execution:
        isolation:
          thread:
            # 缺省为1000
            timeoutInMilliseconds: 10000
          semaphore:
            maxConcurrentRequests: 500
          strategy: SEMAPHORE
      circuitBreaker:
        # 一个统计窗口内熔断触发的最小个数
        requestVolumeThreshold: 300
      fallback:
        enabled: true
        isolation:
          semaphore:
            maxConcurrentRequests: 500
  
  
# httpclient的设置
socialhub:
  # httpclient的参数设置
  httpclient:
    # 连接超时,连接建立时间,三次握手完成时间
    connectTimeout: 6000
    # 设置数据传输过程中数据包之间间隔的最大时间
    socketTimeout: 6000
    # 连接池来管理连接,从连接池获取连接的超时时间
    connectRequestTimeout: 8000
    # 设置重定向
    redirectEnabled: false
    # 连接池的最大连接数
    maxTotal: 1000
    # 连接池按route配置的最大连接数
    defaultMaxPerRoute: 1000
      
      
techsun:
  batch-num: 800
  batch-point-num: 400
  batch-coupon-num: 400
  batch-message-num: 1000
  batch-db-num: 1000
  batch-message-job-num: 2000
  delay-init-minutes: 2
  batch-message-job-sleep: 500
  kafka-message-lock-minutes: 300
  process-message-lock-minutes: 120
  tenant-id: dksst
  #webApi配置租户ID
  urls: member,point,order,config,coupon,marketing
  loyalty-code: TechsunSocialhub-D365-DEV
  exclude:
    #根据逗号分隔
    urls: /v1/events/*,/healthz,/v1/jobs/api/manual
  timeZone: GMT+8
  secret:
    douyin-app-key: 7223642674287363641
    phone-key: 99b198
    mix-key: H10P7x
    # 入参出参敏感信息加密key
    des-key: dksfe172d50c5e829
    aes-key:
    encryptEnum: AES
    enableKms: true
    encryptUrl: http://socialhub-permission-api.crm-dks-prod.svc:8824
  # 定时配置 （ 所有定时时间按北京时间指定 ）
  timing:
    # 心跳：每10秒执行一次
    heartbeat: 0/10 * * * * ? 2100
    # yyyy-MM-dd
    startTime:
    # yyyy-MM-dd
    endTime:
  market-thread-pool:
    corePoolSize: 10
    maximumPoolSize: 20
    queueSize: 5
  job-thread-pool:
    corePoolSize: 1
    maximumPoolSize: 2
    queueSize: 0
  point-thread-pool:
    corePoolSize: 1
    maximumPoolSize: 4
    queueSize: 4
  market-batch-reward-thread-pool:
    corePoolSize: 1
    maximumPoolSize: 2
    queueSize: 200000
  market-batch-message-thread-pool:
    corePoolSize: 1
    maximumPoolSize: 2
    queueSize: 200000
  market-kafka-thread-pool:
    corePoolSize: 1
    maximumPoolSize: 2
    queueSize: 30
  market-message-send-thread-pool:
    corePoolSize: 10
    maximumPoolSize: 20
    queueSize: 20
  market-batch-db-thread-pool:
    corePoolSize: 1
    maximumPoolSize: 1
    queueSize: 200000
  market-batch-reward-coupon-thread-pool:
    corePoolSize: 1
    maximumPoolSize: 2
    queueSize: 20
  market-batch-reward-point-thread-pool:
    corePoolSize: 20
    maximumPoolSize: 40
    queueSize: 100
  amqp:
    enable: true
        
  
  
d365crm:
  resource: https://dks-prod.crm.dynamics.cn
  clientId: 7d30d757-949c-4b39-b0cc-1247e14e2d47
  tenantId: a13e94ef-4057-4b0a-a62b-d2afab85eb73
  secret: vKIdrC48K2P2hZDJOz4i5-_2T~EwD.532b
  # 1：国外  0：国内  默认国内D365
  isGlobal: 0
  
#socialhub-ui 相关配置
socialhub-ui:
  api-url: http://xxx/dev-socialhub-admin
  
#租户ID
tenant:
  #webApi配置租户ID
  urls: member,point,order,config,coupon,marketing
  loyalty-code: TechsunSocialhub-D365-DEV
  exclude:
    #根据逗号分隔
    urls: /v1/events/*,/healthz,/v1/jobs/api/manual
  timeZone: GMT+8
  
framework:
  logging:
    log-switch: true
    #配置日志时区
    timezone: GMT+8
  
  
logging:
  config: classpath:logback-spring-server.xml
  file:
    max-history: 7
    max-size: 100MB
  level:
    com.alibaba.nacos.naming.push: ERROR
    com.alibaba.nacos.client: ERROR
    org.quartz.core: DEBUG
    org.apache.shardingsphere.sql.parser: DEBUG
    org.springframework.util: ERROR
    com.alibaba.nacos: ERROR
    org.quartz.core.QuartzSchedulerThread: ERROR
    com.techsun.techdsadaptor.adaptor.common.utils.DynamicDataSourceUtil: INFO
    com.techsun.socialhub.common.helper.TsCrmBaseHelper: ERROR
    com.azure.messaging.eventhubs.PartitionBasedLoadBalancer: ERROR
    io.netty.resolver.dns: ERROR