server:
  port: 8820
 
spring:
  application:
    name: customer-service
  mvc:
    hiddenmethod:
      filter:
        enabled: true 
 
#socialhub-solution的地址
crm:
  events:
    #url: 'http://localhost:8805/v1'
    url: 'http://customer-event-api.crm-dks-prod.svc:8821'
  marketing:
    url: 'http://marketing-behavior-api.crm-dks-prod.svc:8803'
  customer-datanow:
    url: 'http://customer-datanow-api.crm-dks-prod.svc:8881'
  customer-events:
    url: 'http://customer-event-api.crm-dks-prod.svc:8821'
 
techsun:
  #前端使用socialhub-ui或d365
  front-end:
    names: d365
  local:
    default-date-format: yyyy/MM/dd
    default-date-time-format: yyyy/MM/dd HH:mm:ss
  kms:
    pii:
      managedIdentityClientId: f2cfcf1a-f218-49d0-b933-48c15e1c3af6
      vault: DKS-PROD-KV
      keyName: dks-prod-keys
      keyVersion: fd4c5ad990564a229d8b539fcf170139
      secretName: dks-prod-secret
 
    message:
      mail-sender: ['community@consumerhub.cn']
      user-decryption-field: '{"phone":true,"email":true}'
# DataNow相关配置
datanow:
  # 是否开启推送DataNow
  datanowSwitch: true
  # 推送DataNow Api
  api-url: http://10.12.0.10:50000
  # DataNow标签
  tag-url: http://portraitcenter-api.crm-dks-prod.svc:8880
  # DataNow项目
  project: dksst
 
 
 
#租户ID
tenant:
  exclude:
    #根据逗号分隔
    urls: /v1/events/*,/healthz,/v1/jobs/api/manual
 
sms:
  # UAT环境只有一个通道
  url: 'https://www.futurersms.com/api/sms/send'
  yzm-username: dickiescnapitz
  yzm-password: 7Zl2ev7q
  yx-username: hcrtnfuathy
  yx-password: zxcv1234
  tz-username: hcrtnfuathy
  tz-password: zxcv1234
  startTime: '10:00'
  endTime: '20:00'
  smsSwitch: true
  timeZone: 'Asia/Shanghai'
  verifyMessage: '您的验证码为: %s, 该验证码5分钟内有效, 请勿泄露于他人!'
 
edm:
  edmSwitch: true
  url: 'http://demo6.smartedm.cn:8081/smartedm/services/EDMService'
  displayName: 'dks(test)'
  username: 'dickies'
  password: 'dickies#818526'
 
#标签请求相关配置
label:
  #urlQuery: 'https://clmapi-stg.thenorthface.com.cn/tnf-uat-portraitcenter/'
  urlQuery: 'http://portraitcenter-api.crm-dks-prod.svc:8880'
  urlLogin: 'http://socialhub-permission-api.crm-dks-prod.svc:8824/user/userLogin'
  userName: 'administrator'
  passWord: 'k4u1HiDrlue0mAO43IPFJQ=='
 
shuyun:
  appId: d8d59ebaa40144c5b5e8ffc5c1bb93a4
  # 推送给数云的签名密钥
  secret-security: 5B41E973736B8541D29FA1DBF14A7C23
  # 数云调用天正的签名密钥
  secret-clm: life
  #secret-clm: tnf
  url: http://open-api.shuyun.com
  point-cover: shuyun.loyalty.member.point.cover
  tier-cover: shuyun.loyalty.member.grade.cover
  product-cover: shuyun.base.product.detail.query
  core-pool-size: 6
  max-pool-size: 11
  is-send: prod
  test:
    is-prod-env: true
    accounts:  taqSaAs2
   
miniapp:
  url: 'https://wechatplatform-api.vfc-smart.cn/scrm'
 
wechat:
  token-url: 'https://api.weixin.qq.com/cgi-bin'
  wxAppId: wxd6b962239bd40694
  appId: vfOq0O9XodwJm67Cq0
  appKey: SNm+0EfDrNHitRD33GwtOHeboN7x9pvvJRO6R37f9co=
 
#show sql
logging:
  level:
    com:
      techsun:
        techdsadaptor:
          adaptor:
            jdbc:
              repository:
                mapper: error 
 
#feign开启熔断器
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
  client:
    config:
      default:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        connectTimeout: 10000
        #指建立连接后从服务端读取到可用资源所用的时间
        readTimeout: 20000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
    MemberInfoFeignService#updateMemberTierInfo(TsrMemberInfo):
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000               
http-pool:
  datanow:
    maxTotal: 10
    maxPerRoute: 10
    connectTimeout: 2000
    connReqTimeOut: 40000
    socketTimeout: 300000
    inactivity: 2000