server:
  port: 9921

spring:
  environment: prod
  application:
    name: customer-events-service-tool
  # 邮箱配置
  mail:
    #定时服务
    receiver:
      - 1111@vfc.com

    #后台服务
    receiver2:
      - 1111@vfc.com

    host: smtp.office365.com
    username: techsunDKS8@outlook.com
    password: techsun&DKS
    default-encoding: utf-8
    protocol: smtp
    # 设置TLS认证
    properties:
      mail:
        smtp:
          starttls:
            required: true
    mail-switch: true

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration,com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration

#feign开启熔断器
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
  client:
    config:
      default:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        connectTimeout: 10000
        #指建立连接后从服务端读取到可用资源所用的时间
        readTimeout: 20000
      portraitcenter:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        connectTimeout: 10000
        #指建立连接后从服务端读取到可用资源所用的时间
        readTimeout: 600000
      #admindd365服务设置长一点,部分接口响应很慢
      admin-d365:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        connectTimeout: 10000
        #指建立连接后从服务端读取到可用资源所用的时间
        readTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 120000
    PortraitCenterFeignService#queryResponseMemberAndAmountByProcessIds(MaProcessDto):
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    AdminD365FeignService#query(MarketingInParaDto):
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

customer:
  market-thread-pool:
    corePoolSize: 4
    maximumPoolSize: 8
    queueSize: 20

#socialhub-solution的地址
crm:
  events:
    url: 'http://socialhub-events-api.crm-dks-prod.svc:8805'
  point:
    url: 'http://customer-service-api.crm-dks-prod.svc:8820'
  adminD365:
    url: http://d365-admin-api.crm-dks-prod.svc:8833
  portraitcenter:
    url: http://portraitcenter-api.crm-dks-prod.svc:8880
  app-id: xxxx
  app-key: xxxxx

#sftp
sftp:
  # 地址
  hostname: ftpasia.vfc.com
  # 用户名
  username: Techsun
  # 密码
  password: dOy34fo4
  # 端口号
  port: 22
  # 协议
  protocol: sftp
  # 根目录
  root: /
  # session连接超时时间
  session-connect-timeout: 300000
  # channel连接超时时间
  channel-connected-timeout: 30000
  # DRS存放目录
  drs-path: /local/DRS
  # HEXIF存放目录
  hexif-path: /local/HEXIF
  # exchange文件目录
  exchange-path: /dkscrm_pro/data_exchange/to_techsun/CN/
  #exchange-path: /dkscrm_pro/data_exchange_test/to_techsun/CN/
  # exchange 基础数据目录
  exchange-basic-data-path: /dkscrm_pro/data_exchange/to_techsun/CN/
  #exchange-basic-data-path: /dkscrm_pro/data_exchange_test/to_techsun/CN/
  # archive文件目录
  archive-path: /dkscrm_pro/data_archive/to_techsun/CN/
  #archive-path: /dkscrm_pro/data_archive_test/to_techsun/CN/
  # archive 基础数据目录
  archive-basic-data-path: /dkscrm_pro/data_archive/to_techsun/CN/
  #archive-basic-data-path: /dkscrm_pro/data_archive_test/to_techsun/CN/

techsun:
  #前端使用socialhub-ui或d365
  front-end:
    names: d365
  job-thread-pool:
    corePoolSize: 1
    maximumPoolSize: 2
    queueSize: 0
    #队列类型-目前仅支持eventhub
    #    mq-type: eventhub
    #consumer-group: st

# mule配置信息
mule:
  client-id: 2432ab6a22024a3d9bbe1580dc9b4537
  client-secret: 2FcE647BD7bC4FA5b54221997e13ABd4
  tst-url: https://vf-ap-api-prod-sts-exp.sg-s1.cloudhub.io/api/getSTSToken
  oauth-url: https://vf-ap-api-prod-oauth2-mule4.sg-s1.cloudhub.io/getToken

  sys-id: stsCLM_VANS
  res-sys-id: Aliyun
  oss-endpoint: https://oss-cn-shanghai.aliyuncs.com
  oss-bucket-name: vf-r3-upload-prod
  brand: DKS

# DataNow相关配置
datanow:
  # 是否开启推送DataNow
  datanowSwitch: true
  # 推送DataNow Api
  api-url: http://10.12.0.10:50000
  # DataNow标签
  tag-url: http:/portraitcenter-api.crm-dks-prod.svc:8880
  # DataNow项目
  project: dksst

#租户ID
tenant:
  tenant-id: dksst
  #webApi配置租户ID
  urls: member,point,order,config,coupon
  #加密密钥
  secret2:
    phone-key: key12345
    mix-key: FZYaoV
    # 入参出参敏感信息加密key
    des-key: techsundeskey
    aes-key: 3776d97bbdfb4cec8aac8d4fbecf381e

sms:
  # UAT环境只有一个通道
  url: 'https://www.futurersms.com/api/sms/send'
  yzm-username: dickiescnapitz
  yzm-password: 7Zl2ev7q
  yx-username: dickiescnapiyx
  yx-password: cH7vTe0Q
  tz-username: dickiescnapitz
  tz-password: 7Zl2ev7q
  startTime: '10:00'
  endTime: '22:00'
  smsSwitch: true
  timeZone: 'Asia/Shanghai'

edm:
  edmSwitch: true
  displayName: 'Dickies'
  url: 'http://service.dickies.com.cn:8081/smartedm/services/EDMService'
  username: 'Dickies'
  password: 'DickiesAdmin#2023'

#预流失提醒配置
reminder:
  #微信/线下正价店的短信模板ID
  positive_price_store_template_id: 4fd97dfb-d1c5-ec11-983e-0017fa02a951
  #线下奥莱店对应的短信模板ID
  ole_store_template_id: 21098b13-d2c5-ec11-983e-0017fa02a951
  #微信店铺对应的短信模板ID
  wechat_template_id: 3e38eccd-ab73-ec11-8f8e-0017fa0275f6
  #官网渠道对应的短信模板ID
  officialwebsite-sms-templateid: e702532f-f8c5-ec11-983e-0017fa02a951
  #奥莱店优惠券规则
  ole_store_coupon_rulecode: 2022042700002
  #其他类型店铺优惠券规则
  common_coupon_rulecode: 2022032100002
  #优惠券过期前3天提醒模板ID
  coupon_expires_sms_by_day_templateid: 9298420a-52aa-ec11-b3fe-0017fa03e8ea
  #优惠券过期前30天提醒模板ID
  coupon_expires_sms_by_month_templateid: fae50330-52aa-ec11-b3fe-0017fa03e8ea
  #优惠券过期提醒开始时间 (UTC)
  coupon_expires_start_sendtime: 0 0 2 * * ? *
  #优惠券过期提醒结束时间 (UTC)
  coupon_expires_end_sendtime: 0 0 15 * * ? *
  # 正价店群组id
  positivePriceStoreId: 5871d185-f5c5-ec11-983e-0017fa02a951
  # 奥莱店群组id
  oleStoreId: 3209758f-f5c5-ec11-983e-0017fa02a951
  # 官店网群组id
  officialStoreId: 76dce89b-f5c5-ec11-983e-0017fa02a951
  # 天猫店群组id
  tmallStoreId: bb337da9-f5c5-ec11-983e-0017fa02a951
  # 抖音店群组id
  douyinStoreId: a20e85c8-f5c5-ec11-983e-0017fa02a951
  # 微信店群组id
  wechatStoreId: 0440621d-f3d1-ec11-a7b4-0017fa02596c

#会员升级通知
upgradenotification:
  #通过线下门店注册或绑定微信渠道冒险家
  offlinestoresandwechat-sms-templateid: ae12df36-e8fb-eb11-94ef-0017fa040e6f
  #通过线下门店注册或绑定微信渠道登顶客
  offlinestoresandwechat-summitguest-sms-templateid: ae12df36-e8fb-eb11-94ef-0017fa040e6f
  #是绑定了微信的冒险家
  wechat-sms-templateid: ae12df36-e8fb-eb11-94ef-0017fa040e6f
  #是绑定了微信的登顶客
  wechat-summitguest-sms-templateid: ae12df36-e8fb-eb11-94ef-0017fa040e6f
  #通过官网注册且未绑定微信渠道冒险家
  officialwebsite-sms-templateid: ae12df36-e8fb-eb11-94ef-0017fa040e6f
  #通过官网注册且未绑定微信渠道登顶客
  officialwebsite-summitguest-sms-templateid: ae12df36-e8fb-eb11-94ef-0017fa040e6f
  #天猫且未绑定微信渠道
  tmall-sms-templateid: ae12df36-e8fb-eb11-94ef-0017fa040e6f
  #通过官网注册且未绑定微信渠道对应的冒险家优惠券规则code
  officialwebsite-coupon-rulecode:
    - 2022010600001
  #通过官网注册且未绑定微信渠道对应的登顶客优惠券规则code
  officialwebsite-summitguest-coupon-rulecode:
    - 2022010600001
  #通过线下门店注册或绑定微信渠道对应的冒险家优惠券规则code
  offlinestoresandwechat-coupon-rulecode:
    - 2022010600001
    - 2022010600002
  #通过线下门店注册或绑定微信渠道对应的登顶客优惠券规则code
  offlinestoresandwechat-summitguest-coupon-rulecode:
    - 2022010600001
    - 2022010600002
  #是绑定了微信的对应的冒险家优惠券规则code
  wechat-coupon-rulecode:
    - 2022010600001
  #是绑定了微信的对应的登顶客优惠券规则code
  wechat-summitguest-coupon-rulecode:
    - 2022010600001
  #天猫且未绑定微信渠道对应的冒险家优惠券规则code
  tmall-coupon-rulecode:
    - 2022010600001
  #天猫且未绑定微信渠道对应的登顶客优惠券规则code
  tmall-summitguest-coupon-rulecode:
    - 2022010600001

#积分失效提醒
pointsinvalidreminder:
  #天猫注册且未绑定微信小程序对应的短信模板ID
  tmall-sms-templateid: dd6d686f-ebfb-eb11-94ef-0017fa040e6f
  #注册渠道为线下渠道或绑定微信小程序对应的短信模板ID
  offlinestoresandwechat-sms-templateid: dd6d686f-ebfb-eb11-94ef-0017fa040e6f
  #官网注册且未绑定微信小程序对应的短信模板ID
  officialwebsite-sms-templateid: dd6d686f-ebfb-eb11-94ef-0017fa040e6f

pointnotice:
  get-point-order-templateid: ea0dfff9-fff4-eb11-bacb-0017fa040212
  reduce-point-money-templateid: f64a1e17-c200-ec11-94ef-0017fa03f901

couponnotice:
  consumer-coupon-template-id: c05daa05-0037-ec11-b6e5-0017fa055ec5

#标签请求相关配置
label:
  #urlQuery: 'https://clmapi-stg.thenorthface.com.cn/tnf-uat-portraitcenter/'
  urlQuery: 'http://portraitcenter-api.crm-dks-prod.svc:8880'
  urlLogin: 'http://socialhub-permission-api.crm-dks-prod.svc:8824/user/userLogin'
  userName: 'administrator'
  passWord: 'k4u1HiDrlue0mAO43IPFJQ=='
#miniapp-API
miniapp:
  url: 'https://wechatplatform-api.vfc-smart.cn/scrm'

wechat:
  wechatCommonSwitch: true
  token-url: 'https://api.weixin.qq.com/cgi-bin'
  wxAppId: wxd6b962239bd40694
  appId: vfOq0O9XodwJm67Cq0
  appKey: SNm+0EfDrNHitRD33GwtOHeboN7x9pvvJRO6R37f9co=

d1mtaskstatus:
  #测试环境url
  url: 'https://vans-stg-estore.d1mgroup.com'
  path: '/ht/task/wise_qy_service/member/clm/taskStaffList'
  #每页查询数量
  page-size: 100
  #最大出错次数
  error-num: 10
  #测试环境secret
  secret: 'qywechat@21RaaIMQh3RX9RKH'

need:
  sync:
    class:
      - com.dickies.socialhub.customer.domain.TsrMemberInfo
      - com.dickies.socialhub.common.domain.cosmos.TsrCustomerInfo
shuyun:
  appId: d8d59ebaa40144c5b5e8ffc5c1bb93a4
  # 推送给数云的签名密钥
  secret-security: 5B41E973736B8541D29FA1DBF14A7C23
  # 数云调用天正的签名密钥
  #secret-clm: 0600896436FD1BE057248DB1F6062AA1
  secret-clm: 5B41E973736B8541D29FA1DBF14A7C23
  url: http://open-api.shuyun.com
  point-cover: shuyun.loyalty.member.point.cover
  tier-cover: shuyun.loyalty.member.grade.cover
  order-cover: shuyun.base.order.query.v2
  product-cover: shuyun.base.product.detail.query
  #redis获取时间为null 提前几个小时-到当前时间的订单
  front-time: 2
  #请求出错重试次数
  times-request: 5
  #请求出错休眠几秒
  sleep-second: 3
  point-and-tier-sync-switch: true
  point-all-sync-switch: true
  tier-all-sync-switch: true
  is-send: prod
  #平台编码
  source-codes: 67021780,1522520,103992554

#邮件发送人配置
emailsender:
  #统计报表邮件发送人配置
  count-excel-receiver:
    member-insight-overall:
      - 1111@vfc.com
    member-activity:
      - 1111@vfc.com
    campaign:
      - 111@vfc.com
    coupon-report:
      - 1111@vfc.com
    member-sales-statistical:
      - 111@vfc.com

custom-campaign:
  strategy:
    uppointrecord:
      configs:
        - conditions:
            - key: pointdirection
              operator: eq
              values:
                - 100000000
            - key: transactionid
              operator: 'null'
            - key: $hasFollowGZH
              operator: eq
              values:
                - true
          actions:
            - type: message
              value: 520cb5af-0f76-ed11-81ab-0017fa04956a
        - conditions:
            - key: pointdirection
              operator: eq
              values:
                - 100000001
            - key: transactionid
              operator: 'null'
            - key: $hasFollowGZH
              operator: eq
              values:
                - true
          actions:
            - type: message
              value: cca6823a-1076-ed11-81ab-0017fa04956a
    uppointcount:
      configs:
        - conditions:
            - key: originalPoint
              operator: greaterThan
              values:
                - 0
            - key: transactionId
              operator: notNull
            - key: $hasFollowGZH
              operator: eq
              values:
                - true
          actions:
            - type: message
              value: 520cb5af-0f76-ed11-81ab-0017fa04956a
        - debounce:
            group: DECREASE
            delay: 2000
            key: eventId_transactionId
          conditions:
            - key: originalPoint
              operator: lessThan
              values:
                - 0
            - key: transactionId
              operator: notNull
            - key: $hasFollowGZH
              operator: eq
              values:
                - true
          actions:
            - type: message
              value: cca6823a-1076-ed11-81ab-0017fa04956a
    membertier:
      configs:
        - conditions:
            - key: type
              operator: eq
              values:
                - 100000001
            - key: $hasFollowGZH
              operator: eq
              values:
                - true
          actions:
            - type: message
              value: 2746886a-1076-ed11-81ab-0017fa04956a
    signup:
      configs:
        - debounce:
            delay: 2000
            key: eventId
          conditions:
            - key: dim7
              operator: eq
              values:
                - 0
            - key: $hasFollowGZH
              operator: eq
              values:
                - true
          actions:
            - type: message
              value: e74626b1-d175-ed11-81ab-0017fa0491e3
        - debounce:
            delay: 2000
            key: eventId
          conditions:
            - key: dim7
              operator: eq
              values:
                - 0
            - key: $hasFollowGZH
              operator: eq
              values:
                - false
          actions:
            - type: message
              value: fae74b05-4e7c-ed11-81ad-0017fa0491e3

#优惠券发放/核销消息微信模板ID
preCoup:
  wechat:
    send-templateId: 19d2e0a0-1076-ed11-81ab-0017fa04956a
    hx-templateId: 521dd7e1-1176-ed11-81ab-0017fa04956a

#历史会员积分、等级推送配置，上线后可以删掉，同时也要改后台代码
history:
  shuyun:
    push:
      page-size: 150
      sleep-time: 5
      judge-times: 4
      limit-period: 3
      limit-count: 35

msg-template:
  #首单trigger
  first-order:
    #七天
    seven-day:
      sms: 'deee2e2f-5eb2-ed11-83fe-0017fa05e00f'
      wechat: '38a60f11-5eb2-ed11-83fe-0017fa05e00f'
    #三十天
    thirty-day:
      sms: '7c2a2963-60b2-ed11-83fe-0017fa05e00f'
      wechat: '7308147b-60b2-ed11-83fe-0017fa05e00f'
  #积分临近过期
  point-will-expire:
    thirty-day:
      sms: '5e8db742-686d-ee11-8def-0017fa03252d'
      wechat: ''
      tmall: 'ace6f383-ef8c-ee11-8179-0017fa032cf5'
      tmall-luggage: 'b6ca0035-f18c-ee11-8179-0017fa032cf5'
      douyin: '4abbf2db-656d-ee11-8def-0017fa03252d'
send-time-hour:
  #保级成功提醒
  retention-level-notice: 8
  #优惠券临近过期提醒
  coupon-expire-notice: 10
tier-notify:
  upgrading:
    tierThresholdMapping:
      DH: 500
      DI: 1000
    tierSourceMsgTemplateMapping:
      # DJ:
      #   tmall: ''
      #   gzh: ''
      #   def: ''
      DI:
        tmall: '18d430b2-cab8-ed11-83fe-0017fa0231fc'
        gzh: '65cf1c68-cab8-ed11-83fe-0017fa0231fc'
        def: '65cf1c68-cab8-ed11-83fe-0017fa0231fc'
      DH:
        tmall: '9211469a-cab8-ed11-83fe-0017fa0231fc'
        gzh: 'a503dbdd-c9b8-ed11-83fe-0017fa0231fc'
        def: 'a503dbdd-c9b8-ed11-83fe-0017fa0231fc'
  demoting:
    tierSourceMsgTemplateMapping:
      DJ:
        tmall: 'fdc7ae59-8cb2-ed11-83fe-0017fa05e00f'
        gzh: ''
        def: '36d4ffb0-8bb2-ed11-83fe-0017fa05e00f'
      DI:
        tmall: '8dcfb828-8cb2-ed11-83fe-0017fa05e00f'
        gzh: ''
        def: '4232485c-8bb2-ed11-83fe-0017fa05e00f'
      DH:
        tmall: 'c9a2cd16-8cb2-ed11-83fe-0017fa05e00f'
        gzh: ''
        def: 'c8dae60a-89b2-ed11-83fe-0017fa05e00f'
template-id:
  #预流失
  reminder:
    #1st关注公众号
    bind-wecrm-1st: ''
    #1st未关注公众号
    unbind-wecrm-1st: 6c636e05-5fbd-ed11-83ff-0017fa0231fc
    #1st天猫
    tmall-1st: fa1f6d2a-5fbd-ed11-83ff-0017fa0231fc
    #2nd未关注公众号
    unbind-wecrm-2nd: ''
    #2nd天猫
    tmall-2nd: fd4a7174-4eb3-ed11-83fe-0017fa05e00f
  #优惠券临近过期提醒
  coupon-expire-notice:
    #微信公众号
    bind-wecrm: ''
    #短信
    sms: ca674db3-24b3-ed11-83fe-0017fa05e00f
  #保级成功提醒
  retention-level-notice:
    #微信公众号
    bind-wecrm: eab49873-77b2-ed11-83fe-0017fa05e00f
