server:
  port: 8821

spring:
  environment: uat
  application:
    name: customer-events-service
  # 邮箱配置
  mail:
    receiver:
      #      - VansFamily_NoReply@vfc.com
      #      - poppy@techsun.com
      #      - lida@techsun.com
      #      - lisa@techsun.com
      #      - zoe.zeng@techsun.com
      # - 458838170@qq.com
      # - wenke@techsun.com
      - xuemei@techsun.com
      - carrie@techsun.com
      - tingting@techsun.com
      - Miya_Deng@vfc.com
      - Chenyu_Zhao@vfc.com
    host: smtp.163.com
    username: gongwenke01@163.com
    password: WCRYXVVPAVWBSTHR
    default-encoding: utf-8
    protocol: smtp
    # 设置TLS认证
    properties:
      mail:
        smtp:
          starttls:
            required: true
    mail-switch: true

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration,com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration



customer:
  market-thread-pool:
    corePoolSize: 4
    maximumPoolSize: 8
    queueSize: 20

#socialhub-solution的地址
crm:
  events:
    url: 'http://socialhub-events-api.crm-dks-prod.svc:8805/v1'
  point:
    url: 'http://customer-service-api.crm-dks-prod.svc:8820/v1'
  adminD365:
    url: http://d365-admin-api.crm-dks-prod.svc:8833
  portraitcenter:
    url: http://portraitcenter-api.crm-dks-prod.svc:8880
  app-id: xxxx
  app-key: xxxxx


#sftp
sftp:
  # 地址
  hostname: ftpasia.vfc.com
  # 用户名
  username: Techsun
  # 密码
  password: dOy34fo4
  # 端口号
  port: 22
  # 协议
  protocol: sftp
  # 根目录
  root: /
  # session连接超时时间
  session-connect-timeout: 300000
  # channel连接超时时间
  channel-connected-timeout: 30000
  # DRS存放目录
  drs-path: /local/DRS
  # HEXIF存放目录
  hexif-path: /local/HEXIF
  # exchange文件目录
  #exchange-path: /dkscrm_pro/data_exchange/to_techsun/CN/
  exchange-path: /dkscrm_pro/data_exchange_test/to_techsun/CN/
  # exchange 基础数据目录
  #exchange-basic-data-path: /dkscrm_pro/data_exchange/to_techsun/CN/
  exchange-basic-data-path: /dkscrm_pro/data_exchange_test/to_techsun/CN/
  # archive文件目录
  #archive-path: /dkscrm_pro/data_archive/to_techsun/CN/
  archive-path: /dkscrm_pro/data_archive_test/to_techsun/CN/
  # archive 基础数据目录
  #archive-basic-data-path: /dkscrm_pro/data_archive/to_techsun/CN/
  archive-basic-data-path: /dkscrm_pro/data_archive_test/to_techsun/CN/


techsun:
  #定时任务
  timing:
    # 等级降级提醒 每天1点0分0秒执行
    relegation-remind: 0 0 1 * * ? * 2100
    #积分到期提醒 每天1点0分0秒执行
    point-expire-remind: 0 0 1 * * ? * 2100
    #优惠券到期提醒 每天1点0分0秒执行
    coupon-expire-remind: 0 0 1 * * ? * 2100
    #会员礼遇服务 每天5点0分0秒执行
    member-buy-coupon: 0 0 5 * * ? 2100
    #同步商品记录 每天1点0分0秒执行
    store-synchronous: 0 0 1 * * ?
    #同步门店记录 每天3点0分0秒执行
    product-synchronous: 0 0 3 * * ?
    #同步oss 商品记录 每天3点0分0秒执行
    oss-product-synchronous: 0 0 3 * * ?
    #同步oss 赠商品记录 每天3点0分0秒执行
    oss-gift-product-synchronous: 0 0 3 * * ?
    #更新会员信息-升级所需金额 每天4点0分0秒执行
    update-member-info: 0 0 4 * * ?
    # ttpos订单同步服务
    ttpos: 0 0 0/1 * * ?
    #积分过期定时服务 每月1日执行
    point-expire-service: 0 0 0 0 1/1 ? *
    # 中台正单
    mid-end-sale-order: 0 0 0 * * ?
    #中台拆单合并
    combine-middle-transaction: 0 0 2 * * ?
    # 中台退单
    mid-end-return-order: 0 0 4 * * ?
    #中台拆单退单
    combine-return-middle-transaction: 0 0 6 * * ?
    # 优惠券过期：每天第一秒
    couponexpire: 1 0 0 * * ? *
    # 每分钟0、30秒时执行
    coupon-rule-update-stock: 0,30 * * * * ?
    # 数云订单同步服务 每天1点30分
    shuyunOrder: 0 30 0/1 * * ?
    # 数云订单每日同步服务 每天0点0分
    shuyun-order-day: 0 0 0 * * ?
    # D1M任务状态同步服务 每天0点30分
    d1mTaskStatus: 0 30 0 * * ?

    sms-msg-response:  0,30 * * * * ?
    # 预流失提醒服务 每月的1日 0点0分0秒执行
    reminder: 0 0 0 1 * ?
    # 积分失效提醒服务 每个月最后一天 0点0分0秒执行
    points-invalid-reminder: 0 0 0 L * ?
    # 短信补发 每天13点开始执行
    reissue: 0 0 13 * * ? *
    #优惠券过期前3天提醒 每天4点0分0秒开始执行
    coupon-expires-sms-by-day: 0 30 4 * * ?
    #优惠券过期前30天提醒 每天4点30分0秒开始执行
    coupon-expires-sms-by-month: 0 0 4 * * ?
    # 发送短信定时任务
    messageSend: 0 */5 * * * ?
    #会员等级升降级服务 每1小时执行一次
    tier: 0 0 */1 * * ?
    #会员保级服务1号执行
    retentionLevel: 0 0 1 1 * ?
    # 中台订单同步 每天凌晨执行
    mid-end-order: 0 15 0/1 * * ?
    #同步更新数据到oss
    sync-update-data-toOSS: 0 0 1 * * ?
    # 发出数云token请求 每2天执行1次
    request-shuyun-token: 0 0 0 1/2 * ?
    # 发送运行日志邮件
    send-logs-mail: 0 40 10 * * ? *
    # 发送job监控邮件
    sendJobLogsMail: 0 40 10 * * ? *
    # 本月过期积分计算
    expiring-point: 0 0 0 * * ?
    # 线上订单7天后计算积分
    shuyunOrderCalculatePoint: 0 0 1 * * ?
    # 优惠券规则过期
    couponRuleExpire: 1 0 0/12 * * ?
    #统计上一年平均客单价
    customer-average-per-consumption-amount-last-year: 0 58 23 31 12 ?
    # 微信状态同步
    wechatMsgSync: 0 */5 * * * ?

    #会员报表统计
    #周报:每周一执行
    memberCountTimeForWeek: 0 0 0 ? * MON
    #月报:每月1号执行
    memberCountTimeForMonth: 0 0 0 1 * ?
    #季报:第1、4、7、10月1号执行
    memberCountTimelForSeason: 0 0 0 1 1,4,7,10 ?
    #半年报:第1、7月1号执行
    memberCountTimeForHalfYear: 0 0 0 1 1,7 ?
    #年报:每年1月1号执行
    memberCountTimelForYear: 0 0 0 1 1 ?
    # 退单推积分
    returnOrderSendMq: 0 */5 * * * ?
    #营销活动报表统计邮件
    #每周一凌晨2点执行
    marketStatistical: 0 0 2 ? * MON
  job:
    #同步门店记录
    store-synchronous: false
    #同步商品记录
    product-synchronous: false
    #同步商品记录
    oss-product-synchronous: false
    #赠品商品记录
    oss-gift-product-synchronous: false
    #更新会员信息-升级所需金额 保级所需金额 每天3点0分0秒执行
    update-member-info: true
    # ttpos订单同步服务
    ttpos: false
    # 优惠券过期：每天第一秒
    couponexpire: false
    # 每分钟0、30秒时执行
    coupon-rule-update-stock: false
    # 数云订单同步服务 每天1点30分
    shuyunOrder: false
    # 数云订单每日同步服务 每天0点0分
    shuyun-order-day: false

    sms-msg-response: false
    # 预流失提醒服务 每月的1日 3点0分0秒执行
    reminder: false
    # 积分失效提醒服务 每个月最后一天 0点0分0秒执行
    points-invalid-reminder: false
    # 短信补发 每天10点开始执行
    reissue: false
    #优惠券过期前3天提醒 每天4点0分0秒开始执行
    coupon-expires-sms-by-day: false
    #优惠券过期前30天提醒 每天4点30分0秒开始执行
    coupon-expires-sms-by-month: false
    #会员等级升降级服务 每天2点执行
    tier: true
    #会员保级服务
    retentionLevel: true
    # 中台订单同步 每天凌晨执行
    mid-end-order: false
    #同步更新数据到oss
    sync-update-data-toOSS: false
    # 发出数云token请求 每2天执行1次
    request-shuyun-token: false
    # 发送运行日志邮件
    send-logs-mail: false
    # D1M 任务状态同步服务
    d1mTaskStatus: false
    # 本月过期积分计算
    expiring-point: false
    #线上积分7天后发积分
    shuyunOrderCalculatePoint: false
    # 优惠券规则过期
    couponRuleExpire: false
    #统计上一年平均客单价
    customer-average-per-consumption-amount-last-year: false
    # 微信状态同步
    wechatMsgSyncJob: false
    # 发送job监控邮件
    sendJobLogsMail: false
    # 营销活动统计邮件
    market-statistical: false
    # 退单推积分
    returnOrderSendMq: false

  #前端使用socialhub-ui或d365
  front-end:
    names: d365
  job-thread-pool:
    corePoolSize: 1
    maximumPoolSize: 2
    queueSize: 0
    #队列类型-目前仅支持eventhub
    #    mq-type: eventhub
    #consumer-group: st


# mule配置信息
mule:
  client-id: 2432ab6a22024a3d9bbe1580dc9b4537
  client-secret: 2FcE647BD7bC4FA5b54221997e13ABd4
  tst-url: https://vf-ap-api-prod-sts-exp.sg-s1.cloudhub.io/api/getSTSToken
  oauth-url: https://vf-ap-api-prod-oauth2-mule4.sg-s1.cloudhub.io/getToken

  sys-id: stsCLM_VANS
  res-sys-id: Aliyun
  oss-endpoint: https://oss-cn-shanghai.aliyuncs.com
  oss-bucket-name: vf-r3-upload-prod
  brand: DKS


# DataNow相关配置
datanow:
  # 是否开启推送DataNow
  datanowSwitch: true
  # 推送DataNow Api
  api-url: http://10.12.64.100:50000
  # DataNow标签
  tag-url: http:/portraitcenter-api.crm-dks-prod.svc:8880
  # DataNow项目
  project: dksst


#租户ID
tenant:
  tenant-id: dksst
  #webApi配置租户ID
  urls: member,point,order,config,coupon
  #加密密钥
  secret2:
    phone-key: key12345
    mix-key: FZYaoV
    # 入参出参敏感信息加密key
    des-key: techsundeskey
    aes-key: 3776d97bbdfb4cec8aac8d4fbecf381e


sms:
  # UAT环境只有一个通道
  url: 'https://www.futurersms.com/api/sms/send'
  yzm-username: dickiescnapitz
  yzm-password: 7Zl2ev7q
  yx-username: dickiescnapiyx
  yx-password: cH7vTe0Q
  tz-username: dickiescnapitz
  tz-password: 7Zl2ev7q
  startTime: '10:00'
  endTime: '20:00'
  smsSwitch: false
  timeZone: 'Asia/Shanghai'

edm:
  edmSwitch: false
  displayName: 'dks(test)'
  url: 'http://demo6.smartedm.cn:8081/smartedm/services/EDMService'
  username: 'dickies'
  password: 'dickies#818526'

#预流失提醒配置
reminder:
  #微信/线下正价店的短信模板ID
  positive_price_store_template_id: 4fd97dfb-d1c5-ec11-983e-0017fa02a951
  #线下奥莱店对应的短信模板ID
  ole_store_template_id: 21098b13-d2c5-ec11-983e-0017fa02a951
  #微信店铺对应的短信模板ID
  wechat_template_id: 3e38eccd-ab73-ec11-8f8e-0017fa0275f6
  #官网渠道对应的短信模板ID
  officialwebsite-sms-templateid: e702532f-f8c5-ec11-983e-0017fa02a951
  #奥莱店优惠券规则
  ole_store_coupon_rulecode: 2022042700002
  #其他类型店铺优惠券规则
  common_coupon_rulecode: 2022032100002
  #优惠券过期前3天提醒模板ID
  coupon_expires_sms_by_day_templateid: 9298420a-52aa-ec11-b3fe-0017fa03e8ea
  #优惠券过期前30天提醒模板ID
  coupon_expires_sms_by_month_templateid: fae50330-52aa-ec11-b3fe-0017fa03e8ea
  #优惠券过期提醒开始时间 (UTC)
  coupon_expires_start_sendtime: 0 0 2 * * ? *
  #优惠券过期提醒结束时间 (UTC)
  coupon_expires_end_sendtime: 0 0 15 * * ? *
  # 正价店群组id
  positivePriceStoreId: 5871d185-f5c5-ec11-983e-0017fa02a951
  # 奥莱店群组id
  oleStoreId: 3209758f-f5c5-ec11-983e-0017fa02a951
  # 官店网群组id
  officialStoreId: 76dce89b-f5c5-ec11-983e-0017fa02a951
  # 天猫店群组id
  tmallStoreId: bb337da9-f5c5-ec11-983e-0017fa02a951
  # 抖音店群组id
  douyinStoreId: a20e85c8-f5c5-ec11-983e-0017fa02a951
  # 微信店群组id
  wechatStoreId: 0440621d-f3d1-ec11-a7b4-0017fa02596c

#会员升级通知
upgradenotification:
  #通过线下门店注册或绑定微信渠道冒险家
  offlinestoresandwechat-sms-templateid: ae12df36-e8fb-eb11-94ef-0017fa040e6f
  #通过线下门店注册或绑定微信渠道登顶客
  offlinestoresandwechat-summitguest-sms-templateid: ae12df36-e8fb-eb11-94ef-0017fa040e6f
  #是绑定了微信的冒险家
  wechat-sms-templateid: ae12df36-e8fb-eb11-94ef-0017fa040e6f
  #是绑定了微信的登顶客
  wechat-summitguest-sms-templateid: ae12df36-e8fb-eb11-94ef-0017fa040e6f
  #通过官网注册且未绑定微信渠道冒险家
  officialwebsite-sms-templateid: ae12df36-e8fb-eb11-94ef-0017fa040e6f
  #通过官网注册且未绑定微信渠道登顶客
  officialwebsite-summitguest-sms-templateid: ae12df36-e8fb-eb11-94ef-0017fa040e6f
  #天猫且未绑定微信渠道
  tmall-sms-templateid: ae12df36-e8fb-eb11-94ef-0017fa040e6f
  #通过官网注册且未绑定微信渠道对应的冒险家优惠券规则code
  officialwebsite-coupon-rulecode:
    - 2022010600001
  #通过官网注册且未绑定微信渠道对应的登顶客优惠券规则code
  officialwebsite-summitguest-coupon-rulecode:
    - 2022010600001
  #通过线下门店注册或绑定微信渠道对应的冒险家优惠券规则code
  offlinestoresandwechat-coupon-rulecode:
    - 2022010600001
    - 2022010600002
  #通过线下门店注册或绑定微信渠道对应的登顶客优惠券规则code
  offlinestoresandwechat-summitguest-coupon-rulecode:
    - 2022010600001
    - 2022010600002
  #是绑定了微信的对应的冒险家优惠券规则code
  wechat-coupon-rulecode:
    - 2022010600001
  #是绑定了微信的对应的登顶客优惠券规则code
  wechat-summitguest-coupon-rulecode:
    - 2022010600001
  #天猫且未绑定微信渠道对应的冒险家优惠券规则code
  tmall-coupon-rulecode:
    - 2022010600001
  #天猫且未绑定微信渠道对应的登顶客优惠券规则code
  tmall-summitguest-coupon-rulecode:
    - 2022010600001

#积分失效提醒
pointsinvalidreminder:
  #天猫注册且未绑定微信小程序对应的短信模板ID
  tmall-sms-templateid: dd6d686f-ebfb-eb11-94ef-0017fa040e6f
  #注册渠道为线下渠道或绑定微信小程序对应的短信模板ID
  offlinestoresandwechat-sms-templateid: dd6d686f-ebfb-eb11-94ef-0017fa040e6f
  #官网注册且未绑定微信小程序对应的短信模板ID
  officialwebsite-sms-templateid: dd6d686f-ebfb-eb11-94ef-0017fa040e6f

pointnotice:
  get-point-order-templateid: ea0dfff9-fff4-eb11-bacb-0017fa040212
  reduce-point-money-templateid: f64a1e17-c200-ec11-94ef-0017fa03f901

couponnotice:
  consumer-coupon-template-id: c05daa05-0037-ec11-b6e5-0017fa055ec5


#标签请求相关配置
label:
  #urlQuery: 'https://clmapi-stg.thenorthface.com.cn/tnf-uat-portraitcenter/'
  urlQuery: 'http://portraitcenter-api.crm-dks-prod.svc:8880'
  urlLogin: 'http://socialhub-permission-api.crm-dks-prod.svc:8824/user/userLogin'
  userName: 'administrator'
  passWord: 'k4u1HiDrlue0mAO43IPFJQ=='
#miniapp-API
miniapp:
  url: 'https://wechatplatform-api.vfc-smart.cn/scrm'

wechat:
  wechatCommonSwitch: false
  token-url: 'https://api.weixin.qq.com/cgi-bin'
  wxAppId: wxd6b962239bd40694
  appId: vf5rc9LWuJlgvJ28Hm
  appKey: 4Fio1D7BGODKHYY4ygzO31RPM4HIAM2P5jDD8+29kPc=

d1mtaskstatus:
  #测试环境url
  url: "https://vans-stg-estore.d1mgroup.com"
  path: "/ht/task/wise_qy_service/member/clm/taskStaffList"
  #每页查询数量
  page-size: 100
  #最大出错次数
  error-num: 10
  #测试环境secret
  secret: "qywechat@21RaaIMQh3RX9RKH"

need:
  sync:
    class:
      - com.dickies.socialhub.customer.domain.TsrMemberInfo
      - com.dickies.socialhub.common.domain.cosmos.TsrCustomerInfo
shuyun:
  appId: d8d59ebaa40144c5b5e8ffc5c1bb93a4
  # 推送给数云的签名密钥
  secret-security: 5B41E973736B8541D29FA1DBF14A7C23
  # 数云调用天正的签名密钥
  #secret-clm: 0600896436FD1BE057248DB1F6062AA1
  secret-clm: 5B41E973736B8541D29FA1DBF14A7C23
  url: http://open-api.shuyun.com
  point-cover: shuyun.loyalty.member.point.cover
  tier-cover: shuyun.loyalty.member.grade.cover
  order-cover: shuyun.base.order.query.v2
  product-cover: shuyun.base.product.detail.query
  #redis获取时间为null 提前几个小时-到当前时间的订单
  front-time: 2
  #请求出错重试次数
  times-request: 5
  #请求出错休眠几秒
  sleep-second: 3
  point-and-tier-sync-switch: true
  is-send: prod


#邮件发送人配置
emailsender:
  #统计报表邮件发送人配置
  count-excel-receiver:
    member-insight-overall:
      - jason.z@techsun.com
      - 458838170@qq.com
      - Miya_Deng@vfc.com
      - Chenyu_Zhao@vfc.com
    member-activity:
      - xuemei@techsun.com
      - Miya_Deng@vfc.com
      - Chenyu_Zhao@vfc.com
      - jackhuang@techsun.com
      # - ruiwen@techsun.com
    campaign:
      - xuemei@techsun.com
      - Miya_Deng@vfc.com
      - Chenyu_Zhao@vfc.com
      - ruiwen@techsun.com
      - jason.z@techsun.com
      - Carrie@techsun.com
  

#feign开启熔断器
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: true
  client:
    config:
      default:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        connectTimeout: 10000
        #指建立连接后从服务端读取到可用资源所用的时间
        readTimeout: 20000
      portraitcenter:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        connectTimeout: 10000
        #指建立连接后从服务端读取到可用资源所用的时间
        readTimeout: 30000
      #admindd365服务设置长一点,部分接口响应很慢
      admin-d365:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        connectTimeout: 10000
        #指建立连接后从服务端读取到可用资源所用的时间
        readTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout: 
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    PortraitCenterFeignService#queryResponseMemberAndAmountByProcessIds(MaProcessDto): 
      execution:
        timeout: 
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    AdminD365FeignService#query(MarketingInParaDto): 
      execution:
        timeout: 
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000   

#是否测试环境。生产-false
isTest: false            

#优惠券发放/核销消息微信模板ID
preCoup:
  wechat:
    send-templateId: edabb4e2-d66a-ed11-9562-0017fa0231fc
    hx-templateId: xxxx              