azure:
  #redis信息的配置
  redis:
    host: CRM-DKS-PROD-REDIS.redis.cache.chinacloudapi.cn
    port: 6380
    password: 9qzYYohy9SQFBoE5C7aQZqCzQVrm7Qt3mAzCaOQBEjU=
    ssl: true
    # 连接超时时间（毫秒）
    timeout: 5000
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 11
    # 连接池中的最小空闲连接 默认 0
    min-idle: 20
    # 连接池中的最大空闲连接 默认 8
    max-idle: 50
    # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 10
    max-wait: 5000
    # 连接池最大连接数（使用负值表示没有限制） 默认 8
    max-active: 200
    shutdown-timeout: 100
    expire: 30
common:
  #redis的配置
  redis:
    host: CRM-DKS-PROD-REDIS.redis.cache.chinacloudapi.cn
    port: 6380
    password: 9qzYYohy9SQFBoE5C7aQZqCzQVrm7Qt3mAzCaOQBEjU=
    ssl: true
    # 连接超时时间（毫秒）
    timeout: 5000
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 9
    # 连接池中的最小空闲连接 默认 0
    min-idle: 20
    # 连接池中的最大空闲连接 默认 8
    max-idle: 50
    # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 10
    max-wait: 5000
    # 连接池最大连接数（使用负值表示没有限制） 默认 8
    max-active: 200
    shutdown-timeout: 100
    expire: 30


listener:
  #redis的配置
  redis:
    host: CRM-DKS-PROD-REDIS.redis.cache.chinacloudapi.cn
    port: 6380
    password: 9qzYYohy9SQFBoE5C7aQZqCzQVrm7Qt3mAzCaOQBEjU=
    ssl: true
    # 连接超时时间（毫秒）
    timeout: 5000
    # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    database: 15
    # 连接池中的最小空闲连接 默认 0
    min-idle: 20
    # 连接池中的最大空闲连接 默认 8
    max-idle: 50
    # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 10
    max-wait: 5000
    # 连接池最大连接数（使用负值表示没有限制） 默认 8
    max-active: 200
    shutdown-timeout: 100
    expire: 30
    
spring:
  redis:
    host: CRM-DKS-PROD-REDIS.redis.cache.chinacloudapi.cn
    port: 6380
    password: 9qzYYohy9SQFBoE5C7aQZqCzQVrm7Qt3mAzCaOQBEjU=
    ssl: true
    timeout: 3000 #连接超时时间
    jedis:
      pool:
        max-active: 100 #连接池最大连接数
        max-idle: 20 #连接池中的最大空闲连接
        min-idle: 2 #连接池中的最小空闲连接
        max-wait: 10000 #可用连接的最大等待时间
        time-between-eviction-runs: 6000 #空闲链接检测线程检测周期    