# 创建oap服务
# SW_STORAGE_ES_HTTP_PROTOCOL 默认是 http ，如果ES使用http.ssl,这里设置了 https
# 需要等初始化任务完成之后，才可以启动oap
---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-oap
  namespace: ns-skywalking
  labels:
    app: skywalking
spec:
  type: ClusterIP
  ports:
  - port: 12800
    name: rest
  - port: 11800
    name: grpc
  selector:
    app: skywalking
    component: oap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: skywalking
    component: oap
  name: skywalking-oap
  namespace: ns-skywalking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking
      component: "oap"
  template:
    metadata:
      labels:
        app: skywalking
        component: "oap"
    spec:
      serviceAccountName: skywalking-oap
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: "skywalking"
                  component: oap
      containers:
      - name: oap
        image: phchina/skywalking-oap-server:8.4.0-es7
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 12800
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 12800
          initialDelaySeconds: 15
          periodSeconds: 20
        ports:
        - containerPort: 11800
          name: grpc
        - containerPort: 12800
          name: rest
        resources:
          limits:
            cpu: 2
            memory: 2500Mi
          requests:
            cpu: 1
            memory: 1000Mi
        env:
        - name: JAVA_OPTS
          value: "-Dmode=no-init -Xmx2g -Xms2g"
        - name: SW_CLUSTER
          value: kubernetes
        - name: SW_CLUSTER_K8S_NAMESPACE
          value: "common"
        - name: SW_CLUSTER_K8S_LABEL
          value: "app=skywalking,component=oap"
        - name: SKYWALKING_COLLECTOR_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        #记录数据的有效期，单位天
        - name: SW_CORE_RECORD_DATA_TTL  
          value: "7"
        #分析指标数据的有效期，单位天
        - name: SW_CORE_METRICS_DATA_TTL
          value: "30"
        - name: SW_STORAGE
          value: elasticsearch7
        - name: SW_STORAGE_ES_CLUSTER_NODES
          value: "elasticsearch-master.ns-elastic.svc:9200"
        - name: SW_STORAGE_ES_HTTP_PROTOCOL
          value: "http"
        - name: SW_ES_USER
          value: "elastic"
        - name: SW_ES_PASSWORD
          value: "phNWwVUvE7e9uw6h"