# 创建oap服务
# SW_STORAGE_ES_HTTP_PROTOCOL 默认是 http ，如果ES使用http.ssl,这里设置了 https
# 需要等初始化任务完成之后，才可以启动oap
---
apiVersion: v1
kind: Service
metadata:
  name: skywalking-oap
  namespace: ns-monitor
  labels:
    app: skywalking
spec:
  type: ClusterIP
  ports:
  - port: 12800
    name: rest
  - port: 11800
    name: grpc
  selector:
    app: skywalking
    component: oap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: skywalking
    component: oap
  name: skywalking-oap
  namespace: ns-monitor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: skywalking
      component: "oap"
  template:
    metadata:
      labels:
        app: skywalking
        component: "oap"
    spec:
      serviceAccountName: skywalking-oap
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: "skywalking"
                  component: oap
      containers:
      - name: oap
        #image: apache/skywalking-oap-server:9.5.0
        image: registry.easesaas.com/myron/skywalking-oap-server:9.4.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 12800
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 12800
          initialDelaySeconds: 60
          periodSeconds: 20
        ports:
        - containerPort: 11800
          name: grpc
        - containerPort: 12800
          name: rest
        resources:
          limits:
            cpu: 2
            memory: 6Gi
          requests:
            cpu: 500m
            memory: 4Gi
        env:
        - name: JAVA_OPTS
          value: "-Dmode=no-init -Xmx4g -Xms4g"
        - name: SW_CLUSTER
          value: kubernetes
        - name: SW_CLUSTER_K8S_NAMESPACE
          value: "ns-monitor"
        - name: SW_CLUSTER_K8S_LABEL
          value: "app=skywalking,component=oap"
        - name: SKYWALKING_COLLECTOR_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        #记录数据的有效期，单位天
        - name: SW_CORE_RECORD_DATA_TTL  
          value: "7"
        #分析指标数据的有效期，单位天
        - name: SW_CORE_METRICS_DATA_TTL
          value: "30"
        - name: SW_STORAGE
          value: elasticsearch
        - name: SW_STORAGE_ES_CLUSTER_NODES
          value: "elasticsearch-master-headless.ns-elastic.svc:9200"
        - name: SW_STORAGE_ES_HTTP_PROTOCOL
          value: "http"
        - name: SW_ES_USER
          value: "elastic"
        - name: SW_ES_PASSWORD
          value: "phNWwVUvE7e9uw6h"
        - name: SW_ENABLE_UPDATE_UI_TEMPLATE
          value: "true"
        - name: SW_METER_ANALYZER_ACTIVE_FILES
          value: "datasource,threadpool,satellite,go-runtime,python-runtime,continuous-profiling"
        - name: SW_RECEIVER_GRPC_POOL_QUEUE_SIZE
          value: "50000"
        - name: SW_RECEIVER_GRPC_THREAD_POOL_SIZE
          value: "40"
        volumeMounts:
        - name: alarm-settings-config
          mountPath: /skywalking/config/alarm-settings.yml
          subPath: alarm-settings.yml
        - name: oal-core-config
          mountPath: /skywalking/config/oal/core.oal
          subPath: core.oal
        - name: k8s-service-config
          mountPath: /skywalking/config/otel-rules/k8s/k8s-service.yaml
          subPath: k8s-service.yaml
      hostAliases:
      - hostnames:
        - socialhub-prod-yjd-bastion
        ip: 172.16.0.5
      - hostnames:
        - socialhub-prod-yjd-emr-01
        ip: 172.16.0.10
      - hostnames:
        - socialhub-prod-yjd-emr-02
        ip: 172.16.0.11
      - hostnames:
        - socialhub-prod-yjd-emr-03
        ip: 172.16.0.12
      - hostnames:
        - socialhub-prod-yjd-emr-04
        ip: 172.16.0.13
      - hostnames:
        - socialhub-prod-yjd-emr-05
        ip: 172.16.0.14
      - hostnames:
        - socialhub-prod-yjd-emr-06
        ip: 172.16.0.15
      - hostnames:
        - socialhub-prod-yjd-emr-07
        ip: 172.16.0.16
      - hostnames:
        - socialhub-prod-yjd-stress-01
        ip: 172.16.0.20
      - hostnames:
        - socialhub-prod-yjd-stress-02
        ip: 172.16.0.21
      - hostnames:
        - socialhub-prod-yjd-stress-03
        ip: 172.16.0.22
      volumes:
      - name: alarm-settings-config
        configMap:
          name: alarm-settings-config
          items:
            - key: alarm-settings.yml
              path: alarm-settings.yml
      - name: oal-core-config
        configMap:
          name: sw-oal-config
          items:
            - key: core.oal
              path: core.oal
      - name: k8s-service-config
        configMap:
          name: sw-oal-config
          items:
            - key: k8s-service.yaml
              path: k8s-service.yaml
