apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: blackbox
    app.kubernetes.io/version: 0.16.0
  name: blackbox-exporter
  namespace: ns-monitor
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: blackbox
    spec:
      containers:
      - args:
        - --config.file=/etc/blackbox_exporter/blackbox.yml
        - --log.level=info
        - --web.listen-address=:9115
          #image: prom/blackbox-exporter:v0.24.0
        image: registry.easesaas.com/myron/blackbox-exporter:v0.24.0
        imagePullPolicy: IfNotPresent
        name: blackbox-exporter
        ports:
        - containerPort: 9115
          name: blackbox-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9115
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 30m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/blackbox_exporter
          name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      #hostAliases:
      #- hostnames:
      #  - socialhub-prod-yjd-emr-01
      #  ip: 172.16.0.10
      #- hostnames:
      #  - socialhub-prod-yjd-emr-02
      #  ip: 172.16.0.11
      #- hostnames:
      #  - socialhub-prod-yjd-emr-03
      #  ip: 172.16.0.12
      volumes:
      - configMap:
          defaultMode: 420
          name: blackbox-exporter
        name: config
