# UI安装
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: skywalking
    component: "ui"
  name: skywalking-ui
  namespace: ns-monitor
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 32013
  selector:
    app: skywalking
    component: "ui"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywalking-ui
  namespace: ns-monitor
  labels:
    app: skywalking
    component: "ui"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skywalking
      component: "ui"
  template:
    metadata:
      labels:
        app: skywalking
        component: "ui"
    spec:
      containers:
      - name: ui
        #image: apache/skywalking-ui:9.5.0
        image: registry.easesaas.com/myron/skywalking-ui:9.5.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "1000m"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        ports:
        - containerPort: 8080
          name: page
          protocol: TCP
        env:
        - name: SW_OAP_ADDRESS
          value: http://skywalking-oap.ns-monitor:12800
          
