apiVersion: v1
kind: Service
metadata:
  name: skywalking-oap-nodeport
  namespace: ns-monitor
  labels:
    app: skywalking
spec:
  type: NodePort
  ports:
  - port: 12800
    nodePort: 31280
    name: rest
  - port: 11800
    nodePort: 31180
    name: grpc
  - port: 9090
    nodePort: 31090
    name: promql
  selector:
    app: skywalking
    component: oap
