apiVersion: v1
kind: Service
metadata:
  name: sftp
  namespace: ns-sftp
  labels:
    app: sftp
spec:
  type: ClusterIP
  ports:
  - port: 22
    targetPort: 22
    protocol: TCP
  selector:
    app: sftp
