apiVersion: v1
kind: Secret
metadata:
  name: sftp-secret
  namespace: ns-sftp
  labels:
    app: sftp
type: Opaque
data:
  sftp_user: c29jaWFsaHVi
  sftp_password: UHJvZHlqZEBTb2NpYWxodWIhc2Z0cDIwMjM=
