apiVersion: v1
kind: Service
metadata:
  name: sftp-lb
  namespace: ns-sftp
  labels:
    app: sftp-lb
spec:
  type: NodePort
  ports:
  - port: 22
    nodePort: 32007
    targetPort: 22
    protocol: TCP
  selector:
    app: sftp
