apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  # annotations:
    # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  namespace: ns-nacos
spec:
  type: ClusterIP
  # clusterIP: 10.0.60.60
  # loadBalancerIP: 10.5.60.60
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql-svc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: ns-nacos
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
     labels:
      app: mysql
    spec:
      # hostAliases:
      # - ip: "119.23.114.82"
      #   hostnames:
      #   - "bst.8315.cn"
      containers:
      - name: mysql
        image: mysql:5.7.28
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          protocol: TCP
          name: 3306tcp01
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "ram3yqpa#kb2qXv$"
        args:
          - "--ignore-db-dir=lost+found"
        volumeMounts:
        - name: volumeformysql
          mountPath: /var/lib/mysql
        - name: mysql-cnf
          mountPath: "/etc/mysql/mysql.conf.d/"
      volumes:
      - name: volumeformysql
        persistentVolumeClaim:
          claimName: mysql-datadisk-pvc
      - name: mysql-cnf
        configMap:
          name: mysql-config