apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-datadisk-pvc
  namespace: ns-nacos
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: cephfs
  resources:
    requests:
      storage: 10Gi


