---
apiVersion: v1
kind: Service
metadata:
  name: nacos-nodeport
  namespace: ns-nacos
spec:
  type: NodePort
  selector:
    app: nacos
  ports:
  - port: 8848
    targetPort: 8848
    name: nacos
    nodePort: 32001
